server:
  port: 8081

spring:
  application:
    name: ms-compra
  datasource:
    url: jdbc:mysql://localhost:3306/ms_compra
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /api

